<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../HTML_ImageMap.class.php';

/**
 * Test class for HTML_ImageMap_Area_Circle.
 * Generated by PHPUnit on 2010-04-06 at 14:29:42.
 */
class HTML_ImageMap_Area_CircleTest extends PHPUnit_Framework_TestCase {
    /**
     * @var HTML_ImageMap_Area_Circle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTML_ImageMap_Area_Circle("testname","testhref",array(array(100,100,150,100)));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testAsHTML().
     */
    public function testAsHTML() {
        // Remove the following lines when you implement this test.

        $output = $this->object->asHTML();
        $this->assertEquals($output,'<area id="testname"  href="testhref"    shape="circle" coords="100,100,150,100" />');
    }

    /**
     * @todo Implement testHitTest().
     */
    public function testHitTest() {
        $this->assertTrue( $this->object->hitTest(100,100) );
        $this->assertTrue( $this->object->hitTest(51,100) );
        $this->assertTrue( $this->object->hitTest(149,100) );
        $this->assertTrue( $this->object->hitTest(100,149) );
        $this->assertTrue( $this->object->hitTest(100,51) );

        $this->assertFalse( $this->object->hitTest(49,49) );
        $this->assertFalse( $this->object->hitTest(49,100) );
        $this->assertFalse( $this->object->hitTest(100,151) );
        $this->assertFalse( $this->object->hitTest(149,149) );

    }
}
?>
