<?php
// require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../lib/Weathermap.class.php';

/**
 * Test class for WeatherMapScale.
 * Generated by PHPUnit on 2010-04-06 at 13:31:52.
 */
class WeatherMapScaleTest extends PHPUnit_Framework_TestCase {
    /**
     * @var WeatherMapScale
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // $this->wmap = new Weathermap();
        // $this->object = new WeatherMapScale("testscale", Null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testPopulateDefaults().
     */
    public function testPopulateDefaults() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDrawLegend().
     */
    public function testDrawLegend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddSpan().
     */
    public function testAddSpan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteConfig().
     */
    public function testWriteConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testColourFromValue().
     */
    public function testColourFromValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDrawLegendClassic().
     */
    public function testDrawLegendClassic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDrawLegendVertical().
     */
    public function testDrawLegendVertical() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDrawLegendHorizontal().
     */
    public function testDrawLegendHorizontal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
