<?php
// require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../lib/Weathermap.class.php';

/**
 * Test class for WeatherMapConfigItem.
 * Generated by PHPUnit on 2010-04-06 at 13:31:48.
 */
class WeatherMapConfigItemTest extends PHPUnit_Framework_TestCase {
    /**
     * @var WeatherMapConfigItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WeatherMapConfigItem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
}
?>
