#!/usr/bin/env php
<?php

// PHP Weathermap 1.0.0dev
// Copyright Howard Jones, 2005-2019 howie@thingy.com
// http://www.network-weathermap.com/
// PHP Weathermap is licensed under the MIT License, see LICENSE file for more information.

use Weathermap\CLI\Runner;

require_once __DIR__ . '/lib/all.php';

$run = new Runner();
$run->run();
