<?php
// require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../lib/Weathermap.class.php';

/**
 * Test class for WeatherMap.
 * Generated by PHPUnit on 2010-04-06 at 13:31:46.
 */
class WeatherMapTest extends PHPUnit_Framework_TestCase {
    /**
     * @var WeatherMap
     */
    protected $object;

   
}
?>
