<?php
// require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../lib/HTML_ImageMap.class.php';

/**
 * Test class for HTML_ImageMap_Area.
 * Generated by PHPUnit on 2010-04-06 at 14:29:42.
 */
class HTML_ImageMap_AreaTest extends PHPUnit_Framework_TestCase {
    /**
     * @var HTML_ImageMap_Area
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTML_ImageMap_Area;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testCommon_html().
     */
    public function testCommon_html() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
