<?php
// require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../lib/Weathermap.class.php';

/**
 * Test class for WeatherMapPreProcessor.
 * Generated by PHPUnit on 2010-04-06 at 13:31:50.
 */
class WeatherMapPreProcessorTest extends PHPUnit_Framework_TestCase {
    /**
     * @var WeatherMapPreProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WeatherMapPreProcessor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
