<?php
// require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../lib/Weathermap.class.php';

/**
 * Test class for WeatherMapDataSource.
 * Generated by PHPUnit on 2010-04-06 at 13:31:48.
 */
class WeatherMapDataSourceTest extends PHPUnit_Framework_TestCase {
    /**
     * @var WeatherMapDataSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WeatherMapDataSource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRecognise().
     */
    public function testRecognise() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testReadData().
     */
    public function testReadData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRegister().
     */
    public function testRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPrefetch().
     */
    public function testPrefetch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
